/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdlib.h>
#include <stdio.h>

/* Include memory map of our MCU */
#include <stm32l475xx.h>

/* Include LED driver */
#include "leds.h"
#include "timer.h"

#include "i2c.h"
#include "lsm6dsl.h"

#include <math.h>

#define sensitivity 0.061f


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// Global Variables
volatile uint16_t ct = 0;
volatile uint16_t cyc = 0;
volatile uint16_t i50 = 0;

volatile int16_t pX = 0;
volatile int16_t pY = 0;
volatile int16_t pZ = 0;

uint16_t *count = &ct;
uint16_t *cycles = &cyc;
uint16_t *inc50 = &i50;


int16_t *prevX = &pX;
int16_t *prevY = &pY;
int16_t *prevZ = &pZ;

uint8_t cyclesSaved = 0;

int _write(int file, char *ptr, int len) {
    int i = 0;
    for (i = 0; i < len; i++) {
        ITM_SendChar(*ptr++);
    }
    return len;
}

void TIM2_IRQHandler() {

  	//increment i50
  	((*inc50)++);
	
	if(*inc50 == 100){
		(*cycles)++;
		*inc50 = 0;
	}
	
	if (*cycles >= 12) {
		
		// increment count
		(*count)++;

		if((*count) == 16){
		(*count) = 0;
		}
	}

	
	// manually reset update bit so interrupts can happen again
	TIM2->SR &= ~TIM_SR_UIF;
}

int motion() {

	uint16_t threshold = 3000;

	int16_t x,y,z;

	lsm6dsl_read_xyz(&x, &y, &z);

	// not lost, therefore reset count
	z -= 16550;
	
	if (abs(x - *prevX) * abs(x - *prevX) + abs(y - *prevY) * abs(y - *prevY) + abs(z - *prevZ) * abs(z - *prevZ) > threshold * threshold) {

		*prevX = x;
		*prevY = y;
		*prevZ = z;
		return 1;
	}


	*prevX = x;
	*prevY = y;
	*prevZ = z;
	return 0;
}

int main(void) {
	
  	// initalize LED, Timer, i2c, accel
	leds_init();
	timer_init(TIM2);

	i2c_init();
	lsm6dsl_init();	
	timer_set_ms(TIM2, 50);

	// Initalize Count
	*count = 0;
	uint16_t localCount = 15;
	*cycles = 0;

	uint8_t b1, b2, bits;

	for (;;) {

		// motion detected, reset parameters
		if (motion() == 1) {
			*cycles = 0;
			*inc50 = 0;
			*count = 0;
			localCount = 15;
			leds_set((uint8_t)0);
		}

		// enter lost mode
		if(*cycles >= 12){

			if(localCount != (*count)) {
				uint8_t minutes = (cyclesSaved - 12)/12;

				// Switch case for our preamble AND PID 
				switch(*count){
					// Preamble Segment (0 -> 3)
					case 0:
						cyclesSaved = *cycles;
						leds_set((uint8_t)2);
						break;
					case 1:
						leds_set((uint8_t)1);
						break;
					case 2:
						leds_set((uint8_t)2);
						break;
					case 3:
						leds_set((uint8_t)1);
						break;

					// PID Segment
					// 0 0 0 0 0 0 1 1 1 0 1 1 1 1 1 0
					case 4:
					case 5:
					case 6:
						leds_set((uint8_t)0);
						break;
					case 7:
						leds_set((uint8_t)3);						
						break;
					case 8:
						leds_set((uint8_t)2);
						break;
					case 9:
						leds_set((uint8_t)3);
						break;
					case 10:
						leds_set((uint8_t)3);
						break;
					case 11:
						leds_set((uint8_t)2);
						break;
					 case 12:
					 	// Minutes Segment
    				 	b2 = (minutes & (1 << 7)) >> 6;
					 	b1 = (minutes & (1 << 6)) >> 6;
					 	bits = b2 | b1;
					 	leds_set(bits);
					 	break;
					 case 13:
					 	b2 = (minutes & (1 << 5)) >> 4;
					 	b1 = (minutes & (1 << 4)) >> 4;
					 	bits = b2 | b1;
					 	leds_set((uint8_t)bits);
					 	break;
					 case 14:
					 	b2 = (minutes & (1 << 3)) >> 2;
					 	b1 = (minutes & (1 << 2)) >> 2;
					 	bits = b2 | b1;
					 	leds_set((uint8_t)bits);
					 	break;
					 case 15:
					 	b2 = (minutes & (1 << 1));
					 	b1 = (minutes & (1));
					 	bits = b2 | b1;
					 	leds_set((uint8_t)bits);
					 	break;
				}
				localCount = *count;
			}
		}
	}
  /* Loop forever */
}
